"""empty message

Revision ID: e7ce7a6be958
Revises: afb17b306f1e
Create Date: 2019-01-09 15:33:59.265122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ce7a6be958'
down_revision = 'afb17b306f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_resources_updated_at'), 'resources', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_updated_at'), table_name='resources')
    op.drop_column('resources', 'updated_at')
    # ### end Alembic commands ###
